version: "3.8"

services:
  db:
    image: postgres
    restart: always
    env_file: 
      - db.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  client: 
    container_name: client
    image: client
    build:
      context: ./client
    volumes: 
      - ./client/src:/client/src
    ports:
      - 3000:3000
  api:
    container_name: api
    image: api
    build:
      context: ./server/api
    ports:
      - 3001:3001
volumes:
  db-data: