version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file: 
      - db.env
    ports:
      - 5432:5432
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - network-general
  client: 
    container_name: client
    image: client
    build:
      context: ./client
    volumes: 
      - ./client/src:/client/src
    ports:
      - 3000:3000
  api:
    container_name: api
    image: api
    build:
      context: ./server/api
    ports:
      - 3001:3001
  product:
    container_name: product
    depends_on:
      - db
    image: product
    build:
      context: ./server/product
    volumes:
      - ./.config.json:/product/.config.json
    environment:
      - CONFIG_FILE_PATH=/product/.config.json
    ports:
      - 3002:3002
    networks:
      - network-general
volumes:
  db-data:

networks:
  network-general: